import express from 'express';
import cors from 'cors';
import session from 'express-session';
import path from 'path';
import pluginsRouter from './routes/plugins.js';
import aiRouter from './routes/aiProfiles.js';
import db from './db.js';
import { CONFIG } from './config.js';
const app = express();
app.use(cors({ origin: 'http://localhost:5173', credentials: true }));
app.use(express.json({limit:'20mb'}));
app.use(session({ secret: CONFIG.SESSION_SECRET, resave:false, saveUninitialized:true }));
app.use('/api/plugins', pluginsRouter);
app.use('/api/ai', aiRouter);
import templatesRouter from './routes/templates.js';
app.use('/api/templates', templatesRouter);
app.get('/api/ping', (req,res)=> res.json({ok:true}));
app.use('/', express.static(path.join(process.cwd(), '../frontend/dist')));
app.get('*', (req,res)=> res.sendFile(path.join(process.cwd(), '../frontend/dist/index.html')));
db.initDB().then(()=> app.listen(CONFIG.PORT, ()=> console.log('BotFlow backend listening on', CONFIG.PORT)));
